schema_version = "0.0.1"
smith = "saif-shines/hacksmith-blueprints"


[overview]
title = "Installs brew and sets auto completions"
description = """
A better guide for you to learn using a better package manager and install apps on your MacOS. 
"""
steps = [
  "Installs brew",
  "Identifies the shell environment",
  "Configures completions",
  "Tests the flow"
]

[variables.os]
description = "OS that's being currently operated on"
required = false
sensitive = false

[variables.terminal_client]
description = "Autocompletion is supported in 3 clients — bash, zsh, fish and pwsh"
required = true
sensitive = false

[context.documentation]
primary_docs = "https://docs.brew.sh"
quickstart_guide = "https://docs.brew.sh/Shell-Completion"

[[flows]]

[[flows.steps]]
type = "choice"
title = "Are you on MacOS?"
markdown = """
Brew runs on MacOS only. The future operations hacksmith will execute requires MacOS to set the auto completions.
"""
save_to = "os"
options = ["Yes", "No", "Continue"]



