schema_version = "0.1.0"
smith="saif-shines/hacksmith-blueprints"

[overview]
enabled = true
title = "How to make first API call with You.com (nodejs)"
description = "This blueprint takes you through signing up for You.com account and help you make thef irst API call"
estimated_time = "60s"
steps = [
  "Create account",
  "Login",
  "Get the API Key",
  "Write a script to explain the first API call in Nodejs"
]


[[flows]]
id = "you.com"
title = "Make your first API call with You.com"

[[flows.steps]]
type = "info"
title = "Welcome to You.com"
markdown = """
You are going to review a simple script that uses your You.com account to make a API call and see the list of news articles
"""

[[flows.steps]]
type = "choice"
title = "Do you have You.com account?"
markdown = """
Also, make sure you are signed in to You.com in your current browser session.

"""
save_to = "has_you_dot_com_account"
options = ["Yes", "No"]

[[flows.steps]]
type = "navigate"
title = "Sign up for You.com"
when = "has_you_dot_com_account == 'No'"
url = "{{ slugs.static.home }}"
instructions = [
  "Click on the 'Sign up' button",
  "Complete the signup form",
  "Verify your email",
  "Continue to access your API keys page"
]

[[flows.steps]]
type = "navigate"
title = "Get your API key"
when = "has_you_dot_com_account == 'Yes'"
captures = "api_key"
url = "{{ slugs.static.apikeys_page }}"
instructions = [
  "Sign in if you haven't already",
  "Navigate to the API Keys section",
  "Create a new API key or copy an existing one",
  "Keep it ready for the next step"
]

[[flows.steps]]
type = "input"
title = "Paste your YOU.com API key"
when = "has_you_dot_com_account == 'Yes'"
markdown = """
Paste the API key you just created from the You.com dashboard
"""
save_to = "api_key"


[[flows.steps]]
type = "info"
title = "Writing a script "
markdown = """
run the script, to understand how YOu.com API works and you also make your first API call. Proceed now.
"""


[context.documentation]
primary_docs = "https://documentation.you.com/get-started/welcome"
search_api_doc = "https://documentation.you.com/api-reference/search"

[variables.api_key]
description = "API key from You.com"
required = true
sensitive = true

[slugs]
base_url = "https://you.com"

[slugs.static]
home = "https://you.com/home"
apikeys_page= "https://you.com/platform/api-keys"


[agent]
prompt_template = """
Write a simple and well-commented Node.js script that performs the following steps:

1. Makes an HTTP GET request to a You.com API to fetch the latest news articles.
2. Extracts and displays the headline titles of the most recent articles.
3. Logs the results clearly to the console.
4. Use modern JavaScript (ES6 or later) and async/await syntax.
5. Include clear instructions or comments explaining how to run the script and where to insert the API key if needed.
"""
